import type { Metadata } from "next";
import ContextProviders from "@/contexts";
import "./globals.css";
import Footer from "@/components/organisms/Footer/Footer";
import Navbar from "@/components/organisms/Navbar/Navbar";
import Layout from "@/layout";

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
  authors: { name: "Mahdi FayyaziMoghaddam" },
  icons: {
    icon: "/images/note.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.clear();

  return (
    <html lang="en">
      <head>
        {/* React Scan for Debugging on blow */}
        {/* <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        /> */}
      </head>
      <body
        className="antialiased relative flex flex-col justify-start items-stretch bg-dark-900 text-dark-100 h-screen font-medium overflow-hidden"
        cz-shortcut-listen="true"
        data-gr-ext-installed=""
        contextMenu="none"
      >
        <ContextProviders>
          <Layout>{children}</Layout>
        </ContextProviders>
      </body>
    </html>
  );
}
